"""empty message

Revision ID: 142c33bb2b90
Revises: 82e7b1231b10
Create Date: 2023-07-29 15:47:06.844090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142c33bb2b90'
down_revision = '82e7b1231b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_address')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_address_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'order_addresses', ['order_address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_address_id')

    op.create_table('order_address',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('street_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name='order_address_city_id_fkey'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='order_address_country_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_address_order_id_fkey'),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], name='order_address_street_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_address_pkey')
    )
    op.drop_table('order_addresses')
    # ### end Alembic commands ###
