"""empty message

Revision ID: 49edc7a11ae3
Revises: c91c8659d6c8
Create Date: 2023-07-28 21:35:17.324156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49edc7a11ae3'
down_revision = 'c91c8659d6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('street_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'street', ['street_id'], ['id'])
        batch_op.create_foreign_key(None, 'country', ['country_id'], ['id'])
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('street_id')
        batch_op.drop_column('city_id')
        batch_op.drop_column('country_id')

    op.drop_table('street')
    op.drop_table('city')
    op.drop_table('country')
    # ### end Alembic commands ###
