"""empty message

Revision ID: 4ff5c8b035db
Revises: 7d80011299d4
Create Date: 2023-07-29 20:50:40.055560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff5c8b035db'
down_revision = '7d80011299d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('processed', 'unprocessed', name='orderstatusenum'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_shipping_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('street', sa.String(length=128), nullable=False),
    sa.Column('house_number', sa.String(length=128), nullable=False),
    sa.Column('apartment_number', sa.String(length=128), nullable=False),
    sa.Column('postcode', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_shipping_address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_shipping_address_customer_id'), ['customer_id'], unique=False)

    op.create_table('order_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('cost >= 0', name='check_order_product_cost_non_negative'),
    sa.CheckConstraint('quantity >= 0', name='quantity_positive_or_zero'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_product_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_product_product_id'), ['product_id'], unique=False)

    op.drop_table('product_category')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_name')

    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=140), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name='category_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index('ix_category_name', ['name'], unique=False)

    op.create_table('product_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='product_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_category_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_category_pkey')
    )
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_product_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_product_order_id'))

    op.drop_table('order_product')
    with op.batch_alter_table('customer_shipping_address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_shipping_address_customer_id'))

    op.drop_table('customer_shipping_address')
    op.drop_table('order')
    op.drop_table('customer')
    # ### end Alembic commands ###
