"""empty message

Revision ID: 679c3d7b1630
Revises: 6e0b1368db9e
Create Date: 2023-07-29 19:14:08.216113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679c3d7b1630'
down_revision = '6e0b1368db9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=128), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
