"""empty message

Revision ID: a05b4d2acd8c
Revises: 84dc27f55484
Create Date: 2023-07-27 23:44:49.744683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05b4d2acd8c'
down_revision = '84dc27f55484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_status', sa.Enum('PENDING', 'DELIVERED', 'CANCELLED', name='deliverystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
